image: tkzdockerid/nut-testenv:clang-8-0-A

services:
  - docker:dind

test:debug:
  before_script:
    - docker info
    - export http_proxy="http://proxyout.lanl.gov:8080"
    - export https_proxy="http://proxyout.lanl.gov:8080"
  script:
    - docker run -it tkzdockerid/nut-testenv:clang-8-0-A /bin/bash test_nut.sh


